### ISSUE TITLE
Server e Client ou único projeto?

### ISSUE THREAD

**Issue by paulodiovani** [thatafischer/feevale-multiuserchat-2015#2]
O professor criou o servidor e o cliente em projetos separados. Assim precisa executar o servidor e depois o cliente.

Uma alternativa é fazer num único projeto/aplicativo, deixando iniciar o servidor como uma opção.

Ex:

![mock - chat multiuser](https://cloud.githubusercontent.com/assets/1295197/10655576/a7dc5040-7854-11e5-8538-e117d9ccf89a.jpg)

**Comment by thatafischer** [comment]
Pode ser! Faremos em um único projeto

**Comment by paulodiovani** [comment]
:+1:
